### ISSUE TITLE
OSS Checklist

### ISSUE THREAD

**Issue by jgehring** [facebookresearch/codellama#4]
Things we need to have in place for the release:

- [x] Updated, Llama Code specific README in accordance with blog post and paper (https://github.com/fairinternal/codellama/pull/3 for a start)
- [x] code-specific examples: https://github.com/fairinternal/codellama/pull/7
- [ ] MODEL_CARD.md in sync with the final model card in the paper
- [ ] USE_POLICY.md and LICENSE updates to reflect Llama Code
- [ ] Finalize model naming in download script, sync with #5 
- [ ] Final end-to-end testing with all examples and all respective models
- [ ] remember to push this to facebookresearch/llamacode upon release (I.e. the name of the internal repo is independent of the release one)

See https://docs.google.com/document/d/1aRKA6_BKsLpjNFnA78t89DgaPXQkK_OKnh8SM_z4Uts/edit?usp=sharing for up-to-date details and progress.
